## Run on trusty environment as solr dies all the time on containers after travis move to gce
sudo: required
dist: trusty

language: php

matrix:
    include:
        -
            php: 7.0
            env: TEST_CONFIG="phpunit.xml"
        -
            php: 5.4
            env:
                - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
                - SOLR_VERSION="4.10.4"
                - SOLR_BACKGROUND=true
                - CORES_SETUP="dedicated"
        -
            php: 5.5
            env:
                - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
                - SOLR_VERSION="4.10.4"
                - SOLR_BACKGROUND=true
                - CORES_SETUP="shared"
        -
            php: 5.6
            env:
                - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
                - SOLR_VERSION="4.10.4"
                - SOLR_BACKGROUND=true
                - CORES_SETUP="shared_2"
        -
            php: 5.6
            env:
                - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
                - SOLR_VERSION="4.10.4"
                - SOLR_BACKGROUND=true
                - CORES_SETUP="shared_3"
        -
            php: 7.0
            env:
                - TEST_CONFIG="phpunit-integration-legacy-solr.xml"
                - SOLR_VERSION="4.10.4"
                - SOLR_BACKGROUND=true
                - CORES_SETUP="single"

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - phpenv config-rm xdebug.ini
    - travis_retry composer selfupdate
    # Avoid memory issues on composer install
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer update --prefer-dist --prefer-stable --no-interaction
    - if [ "$SOLR_VERSION" != "" ] ; then ./bin/.travis/init_solr.sh ; fi

script:
    - if [ "$SOLR_VERSION" = "" ] ; then php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c $TEST_CONFIG ; fi
    - if [ "$SOLR_VERSION" != "" ] ; then php -d memory_limit=-1 vendor/bin/phpunit --bootstrap tests/bootstrap.php -c vendor/ezsystems/ezpublish-kernel/$TEST_CONFIG ; fi

notifications:
    email: false
